services:
  # ─────────────── Rails バックエンド ───────────────
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    container_name: rails_api
    ports:
      - "3000:3000"
    volumes:
      - ./backend/Ruby:/var/www/html
    depends_on:
      - db

  # ─────────────── React フロント ───────────────
  frontend:
    build:
      context: ./frontend/react
      dockerfile: ../docker/Dockerfile
    container_name: react_front
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/react:/var/www/html/app
      - /var/www/html/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  #ホットリロード
      - VITE_API_BASE=http://backend:3000
    depends_on:
      - backend

  # ─────────────── PostgreSQL ───────────────
  db:
    image: postgres:16-alpine
    container_name: rails_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passw@rd
      POSTGRES_DB: rails_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    

  # ─────────────── pgAdmin ───────────────
  pgadmin:
    image: dpage/pgadmin4:9.5
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8888:80"                      # http://localhost:8888
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  dbdata:
  pgadmin-data: